export const REGION_NAMES = [
  { name: 'EU', label: 'European Union' },
  { name: 'EFTA', label: 'European Free Trade Association' },
  { name: 'CARICOM', label: 'Caribbean Community' },
  { name: 'PA', label: 'Pacific Alliance' },
  { name: 'AU', label: 'African Union' },
  { name: 'USAN', label: 'Union of South American Nations' },
  { name: 'EEU', label: 'Eurasian Economic Union' },
  { name: 'AL', label: 'Arab League' },
  { name: 'ASEAN', label: 'Association of Southeast Asian Nations' },
  { name: 'CAIS', label: 'Central American Integration System' },
  { name: 'CEFTA', label: 'Central European Free Trade Agreement' },
  { name: 'NAFTA', label: 'North American Free Trade Agreemen' },
  { name: 'SAARC', label: 'South Asian Association for Regional Cooperation' },
];
